# Generated by Django 5.0.6 on 2024-06-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total_dias',
            field=models.FloatField(default=1, verbose_name='Días Totales'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=10, null=True),
        ),
    ]
