# Generated by Django 5.0.6 on 2024-06-04 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField(verbose_name='Fecha de Entrada')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de Salida')),
                ('numero_huespedes', models.IntegerField(verbose_name='Total Huéspedes')),
                ('estado_reserva', models.CharField(choices=[('Activo', 'Activo'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado')], max_length=20, verbose_name='Estado de la Reserva')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.habitacion', verbose_name='Habitación')),
            ],
            options={
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
    ]
