# Generated by Django 5.0.6 on 2024-06-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
    ]
