# Generated by Django 5.0.6 on 2024-06-04 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_habitacion', models.CharField(max_length=10, verbose_name='Habitación #')),
                ('capacidad_maxima', models.IntegerField(verbose_name='Capacidad Máxima')),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Noche')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_habitaciones.tipohabitacion')),
            ],
            options={
                'verbose_name_plural': 'Habitaciones',
                'db_table': 'habitacion',
            },
        ),
    ]
