# Generated by Django 5.0.6 on 2024-06-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True, verbose_name='Clave')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
            ],
            options={
                'verbose_name_plural': 'Configuraciones',
                'db_table': 'sysconfig',
            },
        ),
    ]
